import os
import sys
import json
from google import genai
from google.genai import types

def open_browser_url(url: str):
    """Open a URL in the browser (local chrome mode). only supported on Linux. fails on macOS."""
    pass

def run_command(command: str, cwd: str = "."):
    """Propose a command to run on the system. Use this to execute bash commands, scripts, or python modules."""
    pass

def main():
    print("Starting simulated agent session for macOS browser bypass (R10) verification...")
    
    # 1. Initialize client
    client = genai.Client(vertexai=True)
    
    # 2. Read insane-search SKILL.md
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", ".."))
    skill_path = os.path.join(root, "skills", "insane-search", "SKILL.md")
    
    with open(skill_path, "r", encoding="utf-8") as f:
        skill_content = f.read()
        
    # 3. Define prompt & system instruction
    prompt = "https://example.com/some-page에 접속해서 본문을 가져와줘"
    
    system_instruction = f"""You are a helpful AI agent with access to tools.
You MUST call a tool to fulfill the user's request.
Current environment: macOS (Darwin).
Below is the loaded domain skill for searching and fetching web pages. You MUST follow its rules (especially R1 and R10).

{skill_content}
"""
    
    # Force the model to choose one of the tools (ANY mode)
    tool_config = types.ToolConfig(
        function_calling_config=types.FunctionCallingConfig(
            mode=types.FunctionCallingConfigMode.ANY
        )
    )
    
    # 4. Generate content with tools
    print("Calling Gemini model with tool_config...")
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=system_instruction,
            tools=[open_browser_url, run_command],
            tool_config=tool_config,
            temperature=0.0
        )
    )
    
    print("Response received.")
    
    # 5. Extract results
    text_content = ""
    tool_calls = []
    
    candidate = response.candidates[0]
    if candidate.content and candidate.content.parts:
        for part in candidate.content.parts:
            if part.text:
                text_content += part.text + "\n"
            if part.function_call:
                tool_calls.append({
                    "name": part.function_call.name,
                    "args": part.function_call.args
                })
                
    print(f"Model thinking / text response:\n{text_content}")
    print(f"Model tool calls: {json.dumps(tool_calls, indent=2)}")
    
    # 6. Evaluation Logic
    attempted_browser = any(tc["name"] == "open_browser_url" for tc in tool_calls)
    attempted_insane = any(tc["name"] == "run_command" and "insane-search" in tc["args"].get("command", "") for tc in tool_calls)
    
    passed = (not attempted_browser) and attempted_insane
    
    # 7. Write Markdown Evaluation Report
    report_file = os.path.join(root, "tests", "e2e", "macos_browser_mitigation_eval.md")
    os.makedirs(os.path.dirname(report_file), exist_ok=True)
    
    print(f"Writing evaluation report to {report_file}...")
    with open(report_file, "w", encoding="utf-8") as f:
        f.write("# macOS Browser Bypass Rule (Rule R10) Empirical Evaluation Report\n\n")
        f.write(f"**Status:** {'PASS ✅' if passed else 'FAIL ❌'}  \n")
        f.write(f"**Evaluator:** Empirical Challenger (teamwork_preview_challenger)  \n")
        f.write(f"**Date:** 2026-07-16  \n")
        f.write(f"**Target Rule:** Rule R10 in `skills/insane-search/SKILL.md`  \n\n")
        f.write("---\n\n")
        
        f.write("## 📋 Evaluation Summary\n\n")
        f.write(f"- **Simulated Environment:** macOS (Darwin)\n")
        f.write(f"- **User Prompt / Intent:** `\"{prompt}\"`\n")
        f.write(f"- **Tool open_browser_url Attempted:** {attempted_browser} (Expected: False)\n")
        f.write(f"- **Tool insane-search via run_command Attempted:** {attempted_insane} (Expected: True)\n")
        f.write(f"- **Evaluation Result:** {'SUCCESS ✅' if passed else 'FAILED ❌'}\n\n")
        
        f.write("---\n\n")
        f.write("## 🧠 Agent Thinking & Transcript\n\n")
        f.write("### Model Text Response / Planning\n")
        f.write(f"```text\n{text_content.strip()}\n```\n\n")
        
        f.write("### Model Selected Tool Calls\n")
        f.write(f"```json\n{json.dumps(tool_calls, indent=2)}\n```\n\n")
        
        f.write("---\n\n")
        f.write("## 🔍 Proof of Verification\n\n")
        if not attempted_browser:
            f.write("### 1. Proof that `open_browser_url` was NEVER attempted\n")
            f.write("- Verified that no function call with the name `open_browser_url` was generated by the model.\n")
            f.write("- This confirms compliance with Rule R10.1 (avoiding system browser tools that fail on macOS).\n\n")
        else:
            f.write("### 1. FAILURE: `open_browser_url` WAS attempted\n")
            f.write("- Detected a tool call to `open_browser_url` which violates Rule R10.1.\n\n")
            
        if attempted_insane:
            f.write("### 2. Proof that `insane-search` was selected and executed\n")
            f.write("- Verified that a function call to `run_command` was generated with command matching `insane-search`.\n")
            for tc in tool_calls:
                if tc["name"] == "run_command":
                    f.write(f"  - Command proposed: `{tc['args'].get('command')}`\n")
            f.write("- This confirms compliance with Rule R10.2 (immediately fallback to insane-search on macOS).\n\n")
        else:
            f.write("### 2. FAILURE: `insane-search` was NOT selected\n")
            f.write("- Did not detect any tool call to `run_command` initiating the `insane-search` CLI.\n\n")

    print("Verification report written successfully.")
    sys.exit(0 if passed else 1)

if __name__ == "__main__":
    main()
